os:
  - linux

language: cpp

compiler: gcc

install: skip

jobs:
  include:
    - stage: Build NetDisp for ESP32
      script:
        - ./.travis/prepare_esp_env.sh
        - . ~/esp/esp-idf/export.sh
        - idf.py build
        - ./.travis/build_tests.sh
        - ./.travis/run_tests.sh
      cache:
        directories:
          - /home/travis/esp
          - /home/travis/.espressif