#ifndef NETDISP_CONFIG_HPP
#define NETDISP_CONFIG_HPP

#include <sdkconfig.h>

#define NETDISP_STR_HELPER(x) #x
#define NETDISP_STR(x) NETDISP_STR_HELPER(x)

#ifndef CONFIG_NETDISP_PORT
#define NETDISP_PORT 5432
#else
#define NETDISP_PORT CONFIG_NETDISP_PORT
#endif
#define NETDISP_PORT_STR NETDISP_STR(NETDISP_PORT)

#ifndef CONFIG_NETDISP_WIFI_SSID
#define NETDISP_WIFI_SSID "<SSID>"
#else
#define NETDISP_WIFI_SSID CONFIG_NETDISP_WIFI_SSID
#endif

#ifndef CONFIG_NETDISP_WIFI_PASSWORD
#define NETDISP_WIFI_PASSWORD "<Password>"
#else
#define NETDISP_WIFI_PASSWORD CONFIG_NETDISP_WIFI_PASSWORD
#endif

#ifndef CONFIG_NETDISP_WIFI_MAX_RETRY
#define NETDISP_WIFI_MAX_RETRY 10
#else
#define NETDISP_WIFI_MAX_RETRY CONFIG_NETDISP_WIFI_MAX_RETRY
#endif

#endif // #ifndef NETDISP_CONFIG_HPP